name: Docker Image CI

on:
  push:
    branches:
      - main
      - OCI
env:
  IMAGE_NAME: wilderness95/phpcontactapp
  REGISTRY: docker.io

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run version increment script
      run: ./versionupdater.sh

    - name: Read version.txt
      id: version
      run: echo "::set-output name=version::$(cat version.txt)"

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
      
    - name: Push the  Push
      run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}

    - name: Commit and push version.txt
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add version.txt
        git commit -m "Update version to ${{ steps.version.outputs.version }}"
        git push

    - name: ssh key passphrase
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.GL_SSH_HOST }}
        username: ${{ secrets.GL_SSH_USER }}
        key: ${{ secrets.GL_SSH_SECRET }}
        port: ${{ secrets.GL_SSH_PORT }}
        script: |
          whoami
          ls -al
